### PR TITLE
add Recommendations to main listing when logged in

### PR DESCRIPTION
**Pull request by anxdpanic**
- based on Commit(https://github.com/koying/plugin.video.youtube/commit/962cb18523058d8ab6773e73341da6d447df26f4)

### CODE REVIEW

**Comment by h0d3nt3uf3l** [comment]
This don't give the Channel recommendations back, it gives recommended videos back. Maybe there should be created a new section for, because in a narrow sense its wrong in "Find Channels / Recommended for you". For now I think its okay, but in further I think about a new "Home"-Page in the Plugin, leaned on the YouTube-Website.

**Comment by anxdpanic** [comment]
I can add it to the main page on logged in context as well, or remove it from "recommended for you" and only have it on the main page logged in context. 

Which would you prefer for now? I'll set that up before it's pulled.

**Comment by anxdpanic** [comment]
Second commit adds to main listing, currently left the Recommended for You showing recommendations as well

**Comment by anxdpanic** [comment]
I removed the fill of Recommended for You, and squashed, it's now just adding recommendations to main listing. should be :+1:  now, let me know if any further changes need to be made

**Pull request merged**
